### PR TITLE
Add option to define bar cursor

### PR DESCRIPTION
**Pull request by jrouleau**
Simple feature to allow users to customize the last completed character of the progress bar. Includes logic to remove cursor when bar is complete.

### CODE REVIEW

**Comment by jdan** [comment]
Hmmm, are these used in any CLIs? Nice feature, but I'm not sure how useful it is.

**Comment by jrouleau** [comment]
It's entirely for aesthetics. It's the behaviour of several popular GNU/Linux tools such as `pv` and `wget`.

`pv`
pv

`wget`
wget

However, I'm noticing now that both of these tools keep the cursor as the last character even after the bar is complete. Here is a comparison. I think I actually like keeping this cursor better.

`remove cursor`
cursor-remove

`keep cursor`
cursor-keep


I'm going to update the PR to keep the cursor as that functionality is more common.

**Comment by lbeschastny** [comment]
:+1: not a very important, but definitely a nice feature.

**Comment by ghedamat** [comment]
:+1: as well! let me know if I can help in get this landed

**Pull request closed without merging**
