### PR TITLE
Strip ANSI codes when computing available space. #101

### PR DESCRIPTION
**Pull request by Skywalker13**
It fixes the bar length in the case where colors are used in the
format string.

See #101

### CODE REVIEW

**Comment by Skywalker13** [comment]
ping ?

**Comment by hallas** [comment]
@Skywalker13 

Good with me, just add an example called ansi.js or color.js where you show this working?

**Comment by Skywalker13** [comment]
done

**Comment by Skywalker13** [comment]
@hallas ping :-)

**Comment by Skywalker13** [comment]
@thebigredgeek Why?

**Comment by thebigredgeek** [comment]
Cleaning up our PR backlog and this is quite old.  Will create an issue containing discussion around next major release so that we can get a handle on the every growing API surface area.  We can revisit this at that time

**Pull request closed without merging**
