### PR TITLE
Add a hours:minutes:seconds ETA

### PR DESCRIPTION
**Pull request by cmizzi**
For work projects, I need to use a progress bar with nodeJS and, I think that is could be cool to have a hours, minutes and seconds ETA for long download.

### CODE REVIEW

**Comment by callumlocke** [comment]
+1

**Comment by hallas** [comment]
@jdan Can you take a look?

**Comment by jdan** [comment]
Heya @cmizzi, thanks for the PR.

To be perfectly honest I'm not sure how I feel adding more tokens. I think a better solution might be to just allow users to pass in their own token formatters.

```js
var bar = new ProgressBar('  downloading [:bar] :percent :etas', {
    complete: '=',
    incomplete: ' ',
    width: 20,
    total: len,
    tokens: {
      // maybe not `eta` here specifically...
      ':hour': function(eta) {
        return ...
      }
    }
  });
```

Thoughts?

**Comment by cmizzi** [comment]
It could be a good job but it makes user recreate a child module if they don't want specify each time custom tokens.

**Comment by lbeschastny** [comment]
@jdan totally agree with you about keeping the number of tokens small.

Though, I'll be nice for `node-progress` to pretty-print ETA (either by some flag, or by default).

**Pull request closed without merging**
